providers = ["go"]
[phases.setup]
nixPkgs = [
  "...",
  "tailwindcss",
  "templ",
  "nodejs_18",
] # Install the ffmpeg package from Nix
[phases.install]
cmds = ["npm install", "..."]
[phases.build]
cmds = [
  "npx tailwindcss -i ./main.css -o ./pb_public/main.css",
  "templ generate",
  "...",
]
[start]
cmd = "./out serve --http=0.0.0.0:8090"
runImage = 'debian:bookworm-slim'
onlyIncludeFiles = ['./out', './pb_public']
[variables]
MIGRATE = "false"
ENVIRONMENT = "prod"
