providers = ["go", "node"]

[phases.setup]
nixPkgs = ["...", "tailwindcss", "templ"] # Install the ffmpeg package from Nix
[phases.build]
cmds = [
  "npx tailwindcss -i ./main.css -o ./pb_public/main.css",
  "templ generate",
  "go build -o out",
]
[start]
cmd = "./out serve --http=0.0.0.0:8090"
runImage = 'debian:bookworm-slim'
onlyIncludeFiles = ['./out', './pb_public']
[variables]
MIGRATE = "false"
ENVIRONMENT = "prod"
