[phases.setup]
nixPkgs = ["...", "tailwindcss", "templ"] # Install the ffmpeg package from Nix
aptPkgs = ["...", "npm"]
[phases.build]
cmds = [
  "npm install",
  "tailwindcss -i ./main.css -o ./pb_public/main.css",
  "templ generate",
  "...",
]
[start]
cmd = "./out serve"
[variables]
MIGRATE = "false"
ENVIRONMENT = "prod"
