providers = ["go", "node"]

[phases.setup]
nixPkgs = [
  "...",
  "tailwindcss",
  "templ",
  "curl",
] # Install the ffmpeg package from Nix
[phases.build]
cmds = [
  "npx tailwindcss -i ./main.css -o ./pb_public/main.css",
  "templ generate",
  "go build -o out",
]
[start]
cmd = "./out serve"
[variables]
MIGRATE = "false"
ENVIRONMENT = "prod"
