version: "3"

tasks:
  build:
    cmds:
      - npx tailwindcss -i ./main.css -o ./pb_public/main.css
      - go build -o ./tmp/out .

  run:
    cmds:
      - ./tmp/out serve

  watch:
    cmds:
      - templ generate --watch --proxy="http://localhost:8090" --cmd="task build run"
